name: PR

on:
    pull_request:
        branches: [ master ]

jobs:
    call-pr-workflow:
        uses: AdikaOrg/.github/.github/workflows/pr.yml@main
        with:
            test_task: ":commons:testDebugUnitTest"
